# Information to prompt for and use in wordlist generation
[words]
list = [
       'johann',
       '01-12-1890'
       ]

[results]
max_words = 0 # use 0 for no maximum. Any other number will write the top scoring words into a file.

[print]
shell = false
file = true
dir = '../results/'
fd = 'test_sort.txt'
sort = true
sortby = 'DESC'

[categories]
names = '../categories/names/names.txt'
foods = '../categories/food/food.txt'

[patterns]
birthdate = '(.*)\d+(\.|\/|\-|\_)\d+(\.|\/|\-|\_)\d+(.*)'

# Data that has been pre-processed into formats, chars, etc.
[processed-data]
dir = '../processed/'
format = 'format.txt'
char = 'char.txt'

#####################################
## TO DO: Implement generating rules (quite some work)
[generating-rules]
use-rules = false
max_pwds = 1000000
pattern = 'cccccc' # Allows the program to only generate passwords according to this pattern
#####################################

[common-separators]
list = [
       '.', '-', '/', '*'
       ]

[common-end]
list = [
       '!', '?', '.', '123', '12345'
       ]

[common-replacements] # Based on 1337 dictionary
# Single backslashes are escape characters, which is why a double
# backslash is needed to represent a single backslash. e.q. '/\'=='/\\'
'a' = ['@', '4', '^', '/\\', '/-\\', ''] # = @, 4, ^, /\\, /-\\
'b' = ['l3', '8', '3', 'l', 'ß']
'c' = ['(', '<', '©', '¢']
'd' = ['l)', 'l>', ')']
'e' = ['3', '£', '']
'f' = ['l=', '#', 'ƒ']
'g' = ['6', '9']
'h' = ['#', 'l-l', '(-)', '!-!', '}-{', '}{', 'l+l', ')+(', '!+!', '}+{']
'i' = ['1', '!', '']
'j' = ['_l', '_/']
'k' = ['l<', 'l(', 'l{', 'l<=']
'l' = ['!', 'l_', '1']
'm' = ['l\\/l', '/\\/\\', 'l\\l\\', '^^']
'n' = ['l/l', '/\\/']
'o' = ['0', '()', '<>', '*', 'ø', 'Ó', '°', '']
'p' = ['l*', 'l>', '|D', 'l^', 'l+']
'q' = ['&', '(\\)', '¶']
'r' = ['l2', '®']
's' = ['5', '$', '§']
't' = ['+', '7']
'u' = ['4', 'l_l', '/_/', '']
'v' = [' \\/']
'w' = ['|/\\|', '\\/\\/', '|/\\/', '\\/\\|']
'x' = ['><', '}{', ':-:']
'y' = ['¥', '']
'z' = ['2']
'0' = ['']
'1' = []
'2' = []
'3' = []
'4' = []
'5' = []
'6' = []
'7' = []
'8' = []
'9' = []
'`' = []
'~' = []
'!' = []
'@' = []
'#' = []
'$' = []
'%' = []
'^' = []
'&' = []
'*' = []
'(' = []
')' = []
'-' = ['/', '_', '\\', '.', '|']
'_' = ['/', '-', '\\', '.', '|']
'=' = []
'+' = []
'<' = []
'>' = []
',' = []
'.' = [',', '/', '\\', '*']
'/' = ['-', '_', '.', '\\']
'?' = []
'\\' = ['/'] # (This is a single backslash)
'|' = []
'{' = []
'[' = []
'}' = []
']' = []
';' = []
':' = []
'"' = [''''''']
''''''' = ['"']