# Information to prompt for and use in wordlist generation
[words]
list = [
       'harry', 'potter', 'hogwarts', 'quidditch',
       'hedwig'
       ]

[print]
shell = false
file = true
fd = '../results/test.txt'
sort = true
sortby = 'DESC'

[common-separators]
list = [
       '.', '-', '/', '*'
       ]

[common-end]
list = [
       '!', '?', '.'
       ]

[common-replacements] # Based on 1337 dictionary
# Single backslashes are escape characters, which is why a double
# backslash is needed to represent a single backslash. e.q. '/\'=='/\\'
'a' = ['@', '4', '^', '/\\', '/-\\'] # = @, 4, ^, /\\, /-\\
'b' = ['l3', '8', '3', 'l', 'ß']
'c' = ['(', '<', '©', '¢']
'd' = ['l)', 'l>', ')']
'e' = ['3', '£']
'f' = ['l=', '#', 'ƒ']
'g' = ['6', '9']
'h' = ['#', 'l-l', '(-)', '!-!', '}-{', '}{', 'l+l', ')+(', '!+!', '}+{']
'i' = ['1', '!']
'j' = ['_l', '_/']
'k' = ['l<', 'l(', 'l{', 'l<=']
'l' = ['!', 'l_', '1']
'm' = ['l\\/l', '/\\/\\', 'l\\l\\', '^^']
'n' = ['l/l', '/\\/']
'o' = ['0', '()', '<>', '*', 'ø', 'Ó', '°']
'p' = ['l*', 'l>', '|D', 'l^', 'l+']
'q' = ['&', '(\\)', '¶']
'r' = ['l2', '®']
's' = ['5', '$', '§']
't' = ['+', '7']
'u' = ['4', 'l_l', '/_/']
'v' = [' \\/']
'w' = ['|/\\|', '\\/\\/', '|/\\/', '\\/\\|']
'x' = ['><', '}{', ':-:']
'y' = ['¥']
'z' = ['2']
'0' = []
'1' = []
'2' = []
'3' = []
'4' = []
'5' = []
'6' = []
'7' = []
'8' = []
'9' = []
'`' = []
'~' = []
'!' = []
'@' = []
'#' = []
'$' = []
'%' = []
'^' = []
'&' = []
'*' = []
'(' = []
')' = []
'-' = []
'_' = []
'=' = []
'+' = []
'<' = []
'>' = []
',' = []
'.' = []
'\\' = [] # (This is a single backslash)
'|' = []
'{' = []
'[' = []
'}' = []
']' = []