#!/usr/bin/env python3
from pwd_gen import Pwd_gen
from print_utils import *
from colorama import Fore, Style, Back
import argparse
import toml
import sys

RED = Fore.RED
GREEN = Fore.GREEN
RESET = Style.RESET_ALL

class EntroPass():
    """
    """
    config_fd = '../config/entropass_conf.toml'
    passwords = []
    pass_w_scores = []
    
    def __init__(self):
        """
        """
        try:
            self.config = toml.load(self.config_fd)
            success('Loaded configuration from', self.config_fd)
        except Exception as e:
            error('Could not load', self.config_fd,
                  ':', e)
            sys.exit(1)
        parser = argparse.ArgumentParser(usage='')
        parser.add_argument('-k', '--keywords', required=False)
        args = parser.parse_args()
        self.gen = Pwd_gen(self.config_fd)
        self.seed_words = [word.lower() for word in self.config['words']['list']]

    def run(self):
        """
        """
        self.run_seeding_expanse()
        self.run_permutations()

        self.run_replace()

        self.__rm_duplicates()
        
        if self.config['print']['shell']:
            self.print_passwords()
            cprint('Generated', self.get_count(), 'passwords.')

        if self.config['print']['file']:
            self.write_t_file()
            cprint('Wrote', self.get_count(), 'passwords to', self.config['print']['fd'])
        

    def run_seeding_expanse(self):
        """
        """
        self.passwords.append(self.seed_words)

        for w in self.seed_words:
            res = self.gen.upper_perms(word=w)
            self.passwords.append(res)
        
    def run_permutations(self):
        """
        """
        self.passwords.append(self.gen.word_perms(words=self.seed_words,
                                                  nr_in_result=2))

    def run_replace(self):
        """
        """
        new_psswds = []
        for passwords in self.passwords:
            for p in passwords:
                new_psswds += self.gen.rep_cmmn_chars(word=p,
                                                      iterations=4)

        self.passwords.append(new_psswds)

    def get_count(self):
        """
        """
        count = len(self.passwords)

        return count

    def print_passwords(self):
        """
        """
        print(', '.join(self.passwords))

    def write_t_file(self):
        """
        """
        with open(self.config['print']['fd'], 'w') as fd:
            for p in self.passwords:
                fd.write(p+'\n')

    def __rm_duplicates(self):
        """
        """
        passwords = []
        for ps in self.passwords:
            passwords += ps
        passwords = list(dict.fromkeys(passwords))
        self.passwords = passwords
    
if __name__=='__main__':
    ep = EntroPass()
    ep.run()
